### ISSUE TITLE
mips 设备可以安装但无法运行

### ISSUE THREAD

**Issue by libregratis** [v2rayA/v2raya-openwrt#1]
三台 X86_64 设备 ( Debian 11 / Fedora 34 / OpenWrt 19.07 ) 先后都顺利安装，并运行良好
但在两台 mips 设备上能安装，打不开 UI 界面，检查日志报错：
Wed Dec 22 15:45:05 2021 daemon.err v2raya[3212]: Error relocating /usr/bin/v2raya: __nanosleep_time64: symbol not found
Wed Dec 22 15:45:05 2021 daemon.info procd: Instance v2raya::v2raya s in a crash loop 9 crashes, 0 seconds since last crash
难道是因为 mips 是 32 bit ？
![Screenshot from 2021-12-21 23-06-50](https://user-images.githubusercontent.com/78979149/147051682-04fc19cb-9d52-4179-9a8e-e9b5f6026b5e.png)

**Comment by 1715173329** [comment]
That should be fixed. Try to download from opkg feed.

**Comment by libregratis** [comment]
Working super coooooooool after upgrade to version 1.5.5-3. 
Thx & feliz navidad!

**Comment by 1715173329** [comment]
Merry Christmas~
