### ISSUE TITLE
通过软件源安装失败 iptables-mod-filter 依赖无法安装

### ISSUE THREAD

**Issue by yvvw** [v2rayA/v2raya-openwrt#10]
硬件 nanopi r5s

系统 Linux OpenWrt 5.15.74 #0 SMP PREEMPT Wed Oct 26 14:35:24 2022 aarch64 GNU/Linux

OpenWrt版本 OpenWrt R22.10.20

镜像来源 https://github.com/klever1988/nanopi-openwrt
编译时间 20221027

错误描述：使用软件源安装或手动安装都会遇到 iptables-mod-filter 这个依赖不满足条件安装失败，opkg强制安装v2raya可以运行，luci-app-v2raya页面无法访问，搜了下https://mirrors.cloud.tencent.com/lede/snapshots/targets/rockchip/armv8/kmods/5.15.74-1-6527ad8fb6a8259325809b36d4c2b1ed/ 此内核包含 iptables-mod-filter 这个包，本人openwrt小白不太熟编译这块，到这里就不知道怎么弄了，试了下很多老版本镜像或多或少都有不兼容错误，最新版只有这一个模块不兼容，老版本有些其它的模块也和这个一样

```sh
root@OpenWrt:~# opkg install luci-i18n-v2raya-zh-cn
Multiple packages (libgcc1 and libgcc1) providing same name marked HOLD or PREFER. Using latest.
Installing luci-i18n-v2raya-zh-cn (git-22.251.21862-0f27fe2) to root...
Downloading https://osdn.net/projects/v2raya/storage/openwrt/aarch64_generic/luci-i18n-v2raya-zh-cn_git-22.251.21862-0f27fe2_all.ipk
Installing luci-app-v2raya (5) to root...
Downloading https://osdn.net/projects/v2raya/storage/openwrt/aarch64_generic/luci-app-v2raya_5_all.ipk
Configuring luci-app-v2raya.
Configuring luci-i18n-v2raya-zh-cn.
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.15.74-1-6527ad8fb6a8259325809b36d4c2b1ed) for kmod-ipt-filter
 * pkg_hash_fetch_best_installation_candidate: Packages for kmod-ipt-filter found, but incompatible with the architectures configured
```

```log
No page is registered at '/admin/services/v2raya'.
If this url belongs to an extension, make sure it is properly installed.
If the extension was recently installed, try removing the /tmp/luci-indexcache file.
```

**Comment by 1715173329** [comment]
使用官方 OpenWrt 发行版或自行编译集成 v2rayA。
本项目 LuCI 仅供 OpenWrt 21.02 或以上分支使用。

推荐使用 https://downloads.immortalwrt.org/releases/21.02.3/targets/rockchip
