### ISSUE TITLE
failed to download osdn.net

### ISSUE THREAD

**Issue by ac1595** [v2rayA/v2raya-openwrt#11]
* opkg_install_pkg: Failed to download v2raya. Perhaps you need to run 'opkg update'?
 * opkg_install_cmd: Cannot install package v2raya.
root@OpenWrt:~# opkg update
Downloading https://osdn.net/projects/v2raya/storage/openwrt/mipsel_24kc/Packages.gz
*** Failed to download the package list from https://osdn.net/projects/v2raya/storage/openwrt/mipsel_24kc/Packages.gz

Installing v2raya (1.5.9.1698.1-6) to root...
Downloading https://osdn.net/projects/v2raya/storage/openwrt/mipsel_24kc/v2raya_1.5.9.1698.1-6_mipsel_24kc.ipk
Collected errors:
 * opkg_download: Failed to download https://osdn.net/projects/v2raya/storage/openwrt/mipsel_24kc/v2raya_1.5.9.1698.1-6_mipsel_24kc.ipk, wget returned 4.
 * opkg_download: Check your network settings and connectivity.

**Comment by 1715173329** [comment]
你网烂了。

**Comment by MarksonHon** [comment]
> > 你网烂了。
> 
> 网不烂就不用装这个啦，就一个普通被墙的环境

那就没法子了，手动下载安装包再装吧。

**Comment by 1715173329** [comment]
加了两个镜像地址，还不行的话就只能烧香了。
