### ISSUE TITLE
Sorry Not an issue

### ISSUE THREAD

**Issue by Erwingwapo999** [v2rayA/v2raya-openwrt#13]
Can you add (ssh+custom http payload) or (ssh+direct payload)![Screenshot_2023-01-07-08-27-13-376_com.evozi.injector.png](https://user-images.githubusercontent.com/57695347/211121767-cc58b350-c12f-4d13-89c3-bb3f09ef9bc9.png)

**Comment by Erwingwapo999** [comment]
> What is that?

Add http injection features, like http injector in playstore.
Ssh server + http proxy +payload

**Comment by Erwingwapo999** [comment]
> What is that?

Sorry my English is not good.
Its a vpn tunnel type, here i have show some screenshots in http injector app, ![IMG_20230108_145540.jpg](https://user-images.githubusercontent.com/57695347/211184344-d17cf911-329b-4e03-93fe-5f9df47cc250.jpg)![Screenshot_2023-01-08-14-55-12-755_com.evozi.injector.png](https://user-images.githubusercontent.com/57695347/211184348-3ebc1aff-b333-4a91-8130-d0844b649c23.png)![Screenshot_2023-01-08-14-54-47-869_com.evozi.injector.png](https://user-images.githubusercontent.com/57695347/211184352-9a632c87-9fef-4201-ba7b-621b7dc9ce8b.png)

**Comment by 1715173329** [comment]
I don't think this is something related to my project. This is just an openwrt port for v2rayA.
