### ISSUE TITLE
luci-app-v2raya not available ?

### ISSUE THREAD

**Issue by Ehsan3500** [v2rayA/v2raya-openwrt#14]
Openwrt 22 luci-app-v2raya is not available
already ran v2raya and enabled service but not accessible via router  ip address (192.168.1.1:2017)
Am I missing something ?

**Comment by armineslami** [comment]
Check if it's running using `service` command and if it's not, then use `/etc/init.d/v2raya start` to start it.

**Comment by armineslami** [comment]
> این اوپن چه کارایی مفیدی داره ؟

به طور کلی اجازه میده مدیریت بیشتری روی شبکه داشته باشیم مثل مدیریت روی کاربرها و دیتاها، اجرای انواع پروتکل‌های vpn، نصب adBlock و ...

**Comment by mohamad6663661** [comment]
بسیار عالی تو لینوکس با چه سیستم عاملی میشه نصب کرد؟
امکان داره ایمیل بدید باهاتون در ارتباط باشم ؟

**Comment by armineslami** [comment]
> بسیار عالی تو لینوکس با چه سیستم عاملی میشه نصب کرد؟
> امکان داره ایمیل بدید باهاتون در ارتباط باشم ؟

بله ایمیل داخل پروفایل هست.

**Comment by Ehsan3500** [comment]
> 

openwrt سیستم عامل برای روتر هست که میشه v2ray روش نصب کرد

**Comment by 1715173329** [comment]
It should be http://192.168.1.1:2017 if you're using SSL for LuCI
