### ISSUE TITLE
Cannot install package luci-app-v2raya

### ISSUE THREAD

**Issue by MRdevX** [v2rayA/v2raya-openwrt#15]
Hi, It seems there is an issue with GUI, I'm getting this error while trying to install  luci-app-v2raya.

How can I solve this issue? Are you planning to provide any fixes?

<img width="558" alt="image" src="https://user-images.githubusercontent.com/13729592/216803087-ab9402cf-9e45-4baa-81a5-bf057a725144.png">

**Comment by 1715173329** [comment]
cat /etc/opkg/customfeeds.conf

Show me the output

**Comment by MRdevX** [comment]
> 

![image](https://user-images.githubusercontent.com/13729592/216804888-afe97a75-8823-4308-8da5-db3d8b76eff5.png)

**Comment by 1715173329** [comment]
So your local lists cache is not updated, maybe #12.
Whatever, you can manually download & install it from https://osdn.net/projects/v2raya/storage/openwrt/arm_cortex-a9_vfpv3-d16/luci-app-v2raya_6_all.ipk

**Comment by MRdevX** [comment]
I installed it and now I'm using v2ray on the router. Works like a charm. SUPERB!
