### ISSUE TITLE
Failed to decode signature

### ISSUE THREAD

**Issue by ylu19870105** [v2rayA/v2raya-openwrt#16]
opkg update更新包时提示无法解码签名错误。我已经执行 wget https://osdn.net/projects/v2raya/storage/openwrt/v2raya.pub -O /etc/opkg/keys/94cc2a834fb0aa03下载密钥了。openwrt版本是21.02.5

**Comment by 1715173329** [comment]
装 wget-ssl。

**Comment by ylu19870105** [comment]
>

**Comment by ylu19870105** [comment]
> 装 wget-ssl。

谢谢
