### ISSUE TITLE
luci-app-v2raya 安装之后不显示

### ISSUE THREAD

**Issue by Gaojianli** [v2rayA/v2raya-openwrt#19]
<img width="828" alt="image" src="https://user-images.githubusercontent.com/19235246/226707639-9670bb05-dce6-41fc-b463-a2981e133a2b.png">
如图，已经安装了对应的软件包，但是菜单栏中并没有出现任何与V2rayA相关的选项

**Comment by 1715173329** [comment]
退出重新登录即可（重载 rpcd）

**Comment by Gaojianli** [comment]
> 退出重新登录即可（重载 rpcd）

我是编译安装的这玩意，重启都没用

**Comment by Gaojianli** [comment]
<img width="768" alt="image" src="https://user-images.githubusercontent.com/19235246/226708550-5aebd956-4f85-4b75-a915-3e1997029e75.png">
另外opkg安装会提示我缺少依赖，是因为我这边这个叫 v2raya2的原因吗

**Comment by 1715173329** [comment]
v2raya2 已弃用，请更新你的 feeds

**Comment by Gaojianli** [comment]
> v2raya2 已弃用，请更新你的 feeds

更新了，还是不行。是否不支持lean？

**Comment by 1715173329** [comment]
- luci-app-v2raya 只支持基于 js luci (19.07+) 的版本，lean 的仍在使用基于 17.01 的 lua luci
- 为兼容不同防火墙版本，默认 makefile 已经不带透明代理依赖，构建时需要手动勾选

**Comment by Gaojianli** [comment]
ok，麻烦更新下readme吧（不支持lean这个）
