### ISSUE TITLE
Signature check failed.

### ISSUE THREAD

**Issue by lionkingc** [v2rayA/v2raya-openwrt#21]
-----------------------------------------------------
 OpenWrt 22.03.3, r20028-43d71ad93e
 -----------------------------------------------------
root@OpenWrt:~# wget https://osdn.net/projects/v2raya/storage/openwrt/v2raya.pub -O /etc/opkg/keys/94cc2a834fb0aa03
Downloading 'https://osdn.net/projects/v2raya/storage/openwrt/v2raya.pub'
Connecting to 44.229.120.134:443
Redirected to /projects/v2raya/storage/openwrt/v2raya.pub/ on osdn.net
Writing to '/etc/opkg/keys/94cc2a834fb0aa03'

Download completed (37490 bytes)
root@OpenWrt:~# echo "src/gz v2raya https://osdn.net/projects/v2raya/storage/openwrt/$(. /etc/openwr
t_release && echo "$DISTRIB_ARCH")" | tee -a "/etc/opkg/customfeeds.conf"
src/gz v2raya https://osdn.net/projects/v2raya/storage/openwrt/x86_64
root@OpenWrt:~# opkg update
Downloading https://osdn.net/projects/v2raya/storage/openwrt/x86_64/Packages.gz
Updated list of available packages in /var/opkg-lists/v2raya
Downloading https://osdn.net/projects/v2raya/storage/openwrt/x86_64/Packages.sig
Failed to decode signature
Signature check failed.
Remove wrong Signature file.

**Comment by 1715173329** [comment]
RTFM
