### ISSUE TITLE
请问是否支持 xtls-rprx-vision 下的reality ?

### ISSUE THREAD

**Issue by lionkingc** [v2rayA/v2raya-openwrt#22]
看到别人的配置界面下有flow 选项可以用xtls-rprx-vision
![222](https://user-images.githubusercontent.com/23330617/231414109-1b895170-fc2a-4e8c-af36-6d3425138539.png)

 安装好最新版的基于openwrt 的v2raya和xray , 但设置里没有这个选项

<img width="400" alt="111" src="https://user-images.githubusercontent.com/23330617/231414373-c37e9f5c-8b89-44c6-acea-b72acaf0d0fd.png">

**Comment by 1715173329** [comment]
不支持，欢迎给 v2raya PR

**Comment by SkyWalker1726** [comment]
so v2RayA wont  support "reality" anytime soon ?
