### ISSUE TITLE
安装失败

### ISSUE THREAD

**Issue by iceraintsx** [v2rayA/v2raya-openwrt#25]
在x86_64 openwrt软路由中安装v2rayA报错，内核版本6.1.50：
root@OpenWrt:~# opkg install v2raya
Multiple packages (libgcc1 and libgcc1) providing same name marked HOLD or PREFER. Using latest.
Installing v2raya (2.2.4-1) to root...
Downloading https://mirrors.cloud.tencent.com/lede/snapshots/packages/x86_64/packages/v2raya_2.2.4-1_x86_64.ipk
Configuring v2raya.
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.15.130-1-61d44f65bd1b028e12cc87814825d543) for kmod-nfnetlink
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.15.130-1-61d44f65bd1b028e12cc87814825d543) for kmod-nf-reject
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.15.130-1-61d44f65bd1b028e12cc87814825d543) for kmod-nf-reject6
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.15.130-1-61d44f65bd1b028e12cc87814825d543) for kmod-nf-conntrack
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.15.130-1-61d44f65bd1b028e12cc87814825d543) for kmod-nf-conntrack6
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.15.130-1-61d44f65bd1b028e12cc87814825d543) for kmod-nf-nat
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.15.130-1-61d44f65bd1b028e12cc87814825d543) for kmod-nf-log
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.15.130-1-61d44f65bd1b028e12cc87814825d543) for kmod-nf-log6
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.15.130-1-61d44f65bd1b028e12cc87814825d543) for kmod-crypto-hash
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.15.130-1-61d44f65bd1b028e12cc87814825d543) for kmod-crypto-crc32c
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.15.130-1-61d44f65bd1b028e12cc87814825d543) for kmod-lib-crc32c
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.15.130-1-61d44f65bd1b028e12cc87814825d543) for kmod-nft-core
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.15.130-1-61d44f65bd1b028e12cc87814825d543) for kmod-nf-tproxy
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.15.130-1-61d44f65bd1b028e12cc87814825d543) for kmod-nft-tproxy

**Comment by MarksonHon** [comment]
没事别用 Snapshot 版本的 OpenWrt，如果要用，那就勤更新，以免内核模块不匹配

**Comment by iceraintsx** [comment]
> 没事别用 Snapshot 版本的 OpenWrt，如果要用，那就勤更新，以免内核模块不匹配

大佬，正式版的固件一般用什么比较好？

**Comment by MarksonHon** [comment]
@iceraintsx 如果只是跑个 v2rayA，那么 Open Wrt 官方的稳定版就足够了
