### ISSUE TITLE
无法便用透明代理  failed to start v2ray-core: not support "redirect" mode of transparent proxy:

### ISSUE THREAD

**Issue by glenlau228** [v2rayA/v2raya-openwrt#26]
failed to start v2ray-core: not support "redirect" mode of transparent proxy: ExecCommands: iptables -w 2 -t nat -N TP_OUT iptables v1.8.7 (legacy): can't initialize iptables table `nat': Table does not exist (do you need to insmod?) Perhaps iptables or your kernel needs to be upgraded. : exit status 3

这是因为没有安装  v2ray-core 吗？ 还是没有配置好 iptables  , 请指教下，

目前只有关闭第一项，开启端口分享，利用 [SwitchyOmega] 插件可正常上外网。

IP转发 不起作用

OpenWrt 22.03.5 r20134-5f15225c1e

**Comment by mmmjie** [comment]
同样的问题

**Comment by MarksonHon** [comment]
https://github.com/v2rayA/v2raya-openwrt/

按照要求安装模块后重启设备
