### ISSUE TITLE
代理后分流的国服游戏延迟增加了20多。。。

### ISSUE THREAD

**Issue by mmmjie** [v2rayA/v2raya-openwrt#27]
配置的日本代理，代理后延迟从游戏40变为160
分析后游戏IP 数据库显示香港，其实是广州
我用RoutingA分流香港走直连后，延迟从160变成60多，还是多了20

这20多是走代理代理内核，哪怕分流到直连也会增加的吗？
 用的是xray内核，Tproxy模式，协议是vless,无加密伪装

**Comment by mmmjie** [comment]
我困惑的是，是不是用这个插件，必定会增加20？不管直连还是代理

**Comment by 1715173329** [comment]
开启后流量全部过 core，增加延迟说明设备太烂。
可以自行手动配置防火墙规则绕过。
你的这个 issue 与本仓库无关。
