### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by ring0li** [v2rayA/v2raya-openwrt#39]
wget-ssl libustream在openwrt的软件包管理里都安装了，软件包安装v2raya失败，命令行也失败。。。 

[root@OpenWrt:10:48 AM ~] # opkg install v2raya
Installing v2raya (2.2.4.6-251) to root...
Segmentation fault

**Comment by MarksonHon** [comment]
![图片](https://github.com/v2rayA/v2raya-openwrt/assets/50002150/b6475cf8-25d6-4b4b-8296-530cd724d7f7)
