### ISSUE TITLE
能否通过特定的shell脚本来初始化配置？

### ISSUE THREAD

**Issue by JiaY-shi** [v2rayA/v2raya-openwrt#40]
在openwrt中，如果频繁刷机测试固件的话，每次刷好固件后都需要手动去配置v2ray，比较麻烦，常规的做法是写一个特定的shell脚本放到/etc/uci-defaults中，让系统首次启动时来初始化一些配置，请问v2ray是否可以利用这种方式来初始化账号、密码、订阅地址等一些配置？

**Comment by MarksonHon** [comment]
这里是v2rayA的OpenWrt仓库，不提供对v2ray核心的帮助。不过，你可以在刷机之前先下载好配置文件备份，刷机后再上传回去，这是OpenWrt本身就有点功能。
另外，就算是v2rayA，也没法通过uci来初始化，v2rayA的数据全部存在数据库文件里面
