### ISSUE TITLE
OpwnWrt运行V2rayA后向日葵无法远程

### ISSUE THREAD

**Issue by fzxlzy** [v2rayA/v2raya-openwrt#46]
OpwnWrt运行V2rayA后向日葵无法远程其他电脑
请问如何配置可以使用向日葵

**Comment by aiamadeus** [comment]
参考 https://github.com/v2rayA/v2rayA/discussions/1361
添加自定义 hook `vi /etc/v2raya/core-hook.sh`
```bash
#!/bin/sh

echo hook
jq '.inbounds[] |= if (.tag | index("transparent") >= 0) then (.sniffing.domainsExcluded = ["regexp:^[a-z0-9-]+\\.[a-z0-9-]+\\.oray\\.com$"]) else . end' /etc/v2raya/config.json > /etc/v2raya/temp.json
mv /etc/v2raya/temp.json /etc/v2raya/config.json
```
`chmod +x /etc/v2raya/core-hook.sh`
启用 hook `vi /etc/config/v2raya`:
`option core_hook '/etc/v2raya/core-hook.sh'`

**Comment by improve100** [comment]
我按你方法试了，还是用不了

**Comment by Fisummer** [comment]
> 我按你方法试了，还是用不了

我试了，可以，可能你操作有问题
