### ISSUE TITLE
初次启动时请不要下载 geoip/geosite

### ISSUE THREAD

**Issue by xialvjun** [v2rayA/v2raya-openwrt#47]
初次启动时要下载 geoip/geosite，下载它俩要先科学上网。“鸡生蛋蛋生鸡”了属于是。

我现在是在 openwrt 系统-启动项 里 临时加 export https_proxy ，之后再删掉。但这样总归很麻烦。

能一开始不下载 geoip/geosite 吗。进入 v2raya web 控制台，加上节点后，选择全局，之后自己再点击来下载吗？

**Comment by MarksonHon** [comment]
自己安装对应的包，软件源里面有
