### ISSUE TITLE
error

### ISSUE THREAD

**Issue by mlboy** [v2rayA/v2raya-openwrt#5]
Multiple packages (libgcc1 and libgcc1) providing same name marked HOLD or PREFER. Using latest.
Installing v2raya (1.5.7-5) to root...
Downloading https://mirrors.tuna.tsinghua.edu.cn/osdn/storage/g/v/v2/v2raya/openwrt/x86_64/v2raya_1.5.7-5_x86_64.ipk
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.111-1-6703dcafaa268bc75821eea0f02b92ca) for kmod-nf-reject
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.111-1-6703dcafaa268bc75821eea0f02b92ca) for kmod-nf-ipt
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.111-1-6703dcafaa268bc75821eea0f02b92ca) for kmod-nf-log
 * pkg_hash_fetch_best_installation_candidate: Packages for kmod-nf-log found, but incompatible with the architectures configured
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.111-1-6703dcafaa268bc75821eea0f02b92ca) for kmod-ipt-core
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.111-1-6703dcafaa268bc75821eea0f02b92ca) for kmod-nf-conntrack
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.111-1-6703dcafaa268bc75821eea0f02b92ca) for kmod-ipt-conntrack
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.111-1-6703dcafaa268bc75821eea0f02b92ca) for kmod-ipt-conntrack-extra
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.111-1-6703dcafaa268bc75821eea0f02b92ca) for kmod-ipt-raw
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.111-1-6703dcafaa268bc75821eea0f02b92ca) for kmod-ipt-extra
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.111-1-6703dcafaa268bc75821eea0f02b92ca) for kmod-lib-textsearch
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.111-1-6703dcafaa268bc75821eea0f02b92ca) for kmod-ipt-filter
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.111-1-6703dcafaa268bc75821eea0f02b92ca) for kmod-nf-tproxy
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.111-1-6703dcafaa268bc75821eea0f02b92ca) for kmod-ipt-tproxy
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.111-1-6703dcafaa268bc75821eea0f02b92ca) for kmod-nf-nat
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.111-1-6703dcafaa268bc75821eea0f02b92ca) for kmod-nf-nat6
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.111-1-6703dcafaa268bc75821eea0f02b92ca) for kmod-ipt-nat
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.111-1-6703dcafaa268bc75821eea0f02b92ca) for kmod-nf-reject6
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.111-1-6703dcafaa268bc75821eea0f02b92ca) for kmod-nf-log6
 * pkg_hash_fetch_best_installation_candidate: Packages for kmod-nf-log6 found, but incompatible with the architectures configured
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.111-1-6703dcafaa268bc75821eea0f02b92ca) for kmod-nf-ipt6
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.111-1-6703dcafaa268bc75821eea0f02b92ca) for kmod-ip6tables
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.111-1-6703dcafaa268bc75821eea0f02b92ca) for kmod-ipt-nat6
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for v2raya:
 * 	kernel (= 5.10.111-1-6703dcafaa268bc75821eea0f02b92ca)
 * opkg_install_cmd: Cannot install package v2raya.

**Comment by MarksonHon** [comment]
@mlboy Flash latest OpenWrt firmware to your device and try again

**Comment by mlboy** [comment]
opkg install kmod

**Comment by 1715173329** [comment]
安装最新的稳定版固件，或者自行编译。
